[tool.poetry]
name = "star_rail"
version = "2.1.1"
description = "Honkai: Star Rail Gacha Record Export Tools"
authors = ["Charlie Brown <cntvc@outlook.com>"]
license = "GPLv3"
readme = "README.md"
repository = "https://github.com/cntvc/star-rail-tools"
packages = [{include = "star_rail"}]


[tool.poetry.dependencies]
python = ">=3.11,<3.13"
loguru = "^0.7.2"
requests = "^2.31.0"
xlsxwriter = "^3.1.7"
pydantic = "^2.4.2"
pyperclip = "^1.8.2"
yarl = "^1.9.2"
rich = "^13.6.0"
pycryptodome = "^3.19.0"


[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.9.1"
flake8 = "^6.1.0"
pre-commit = "^3.4.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
pytest-cov = "^4.1.0"


[tool.poetry.group.release.dependencies]
pyinstaller = "^6.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
line_length = 100
profile = "black"


[tool.black]
line-length = 100
