[tool.poetry]
name = "star_rail"
version = "3.0.0"
description = "Honkai: Star Rail Toolkit"
authors = ["Charlie Brown <cntvc@outlook.com>"]
license = "GPLv3"
readme = "README.md"
repository = "https://github.com/cntvc/star-rail-tools"
packages = [{include = "star_rail"}]


[tool.poetry.dependencies]
python = ">=3.11,<3.13" # pyinstaller requires ">=3.11,<3.13"
loguru = "^0.7.2"
pydantic = "^2.5.1"
aiohttp = "^3.9.0"
yarl = "^1.9.2" # subdependencies for aiohttp
aiosqlite = "^0.19.0"
pyperclip = "^1.8.2"
xlsxwriter = "^3.1.9"
textual = "^0.41.0"
pycryptodome = "^3.19.0"


[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.11.0"
flake8 = "^6.1.0"
pre-commit = "^3.5.0"
textual-dev = "^1.2.1"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
pytest-asyncio = "^0.21.1"


[tool.poetry.group.release.dependencies]
pyinstaller = "^6.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
line_length = 100
profile = "black"


[tool.black]
line-length = 100

[tool.pytest.ini_options]
addopts = ["-vs"]
asyncio_mode = "auto"

[tool.coverage.run]
omit = [
    "**/__init__.py",
    "**/mapper.py",
    "exceptions.py",
    "main.py",
]
