name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:


permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.11
          cache: true
      - name: Install dependencies
        run: pdm sync --with lint --no-default
      - name: Run lint
        run: pdm run lint
